### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by Polarisation** [dmkit/phalcon-jwt-auth#15]
I'd like to use this, but I'd need to be able to tick the licensing box. Is it possible to add a license? MIT/BSD or similar would be good (Phalcon itself uses New BSD)

**Comment by dmkit** [comment]
I'm actually not super familiar with this licensing thing. May I know why you would require it?

**Comment by Polarisation** [comment]
Without a license, it's not clear who has permission to use this library and under what conditions.
See this explanation: https://help.github.com/articles/licensing-a-repository/

> For your repository to truly be open source, you'll need to license it so that others are free to use, change, and distribute the software.

The most popular license type on GitHub is MIT (from https://github.com/blog/1964-open-source-license-usage-on-github-com).

**Comment by Polarisation** [comment]
Step-by-step instructions here: https://help.github.com/articles/adding-a-license-to-a-repository/

**Comment by dmkit** [comment]
I see. I just added it.
