### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by rafaelmenon** [dmkit/phalcon-jwt-auth#18]
Hello I am having problems implementing jwt in phalcon, I am importing as described: "use Dmkit \ Phalcon \ Auth \ Middleware \ Micro as AuthMicro;" but I have the return: "Uncaught Error: Class 'Dmkit \ Phalcon \ Auth \ Middleware \ Micro' not found in /var/www/html/b9Back/public/index.php:63" Here is line 63: "$ auth = new AuthMicro ($ app, $ authConfig); "

**Comment by dmkit** [comment]
are you using composer?

**Comment by rafaelmenon** [comment]
yes

**Comment by dmkit** [comment]
Have you done this https://www.learnphalcon.com/post/show/22/using-composer-to-install-3rd-party-components---step-2---installing-swiftmailer ? Is this the only composer plugin that you're currently using?

**Comment by rafaelmenon** [comment]
I am wanting to use the library for jwt authentication, I am not using this.

**Comment by dmkit** [comment]
By default composer file autoload doesn't work with phalcon. You will have to implement the link I pasted. This is not an issue with the library. Try looking up "composer autoload with phalcon". I'm closing this issue.
