### ISSUE TITLE
PHP 5.5 Compatibility

### ISSUE THREAD

**Issue by emog** [dmkit/phalcon-jwt-auth#3]
Do you plan to make a php5.6 compatibility ?

**Comment by dmkit** [comment]
The current codebase relies heavily on PHP 7 (closure, array constructors, etc). If you want you can start this project and I will help along the way :)?

**Comment by emog** [comment]
I used your code and made another composer package which support php 5.6.x. It's better for all users to have version for php5.6. If they use php7 they will use your version if they use php5.6.x then they should use my version. Thank you

**Comment by dmkit** [comment]
what's the package name?

**Comment by dmkit** [comment]
You should update your doc that it supports version 5.6 and it was fork by this repo and stuff like that to avoid confusions from other users. Thanks
