### ISSUE TITLE
Add the package to packagist.org

### ISSUE THREAD

**Issue by kaioken** [dmkit/phalcon-jwt-auth#4]
hey @dmkit any plans on adding on doing this?
```
  [InvalidArgumentException]
  Could not find package dmkit/phalcon-jwt-auth at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability
```

had to install the package by adding the git link to my composer.json

Thanks and I'll be submitting PR to update the package to jwt 5 ;)

**Comment by dmkit** [comment]
oh yeah! Will probably do a release :). Thanks!
